### Clone repo and setup

In [1]:
!git clone https://github.com/ThuyHaLE/FRAS.git
%cd FRAS

Cloning into 'FRAS'...
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 230 (delta 105), reused 196 (delta 74), pack-reused 0 (from 0)
Receiving objects: 100% (230/230), 1.74 MiB | 20.94 MiB/s, done.
Resolving deltas: 100% (105/105), done.

In [3]:
!pip -q install -r requirements.txt

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 89.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 104.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.1/222.1 kB 14.6 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done

In [3]:
import pandas as pd
from features import BASE_FEATURES, TARGET_TIME, TARGET_EVENT
from models.utils.enrich_features import enrich_features
from models.utils.filter_features import _TrainerWrapper, filter_features
from models.strategies import (
    ModelStrategy,
    RSFStrategy,
    GradBoostStrategy,
    CoxnetStrategy,
    CGBStrategy,
    _STRATEGY_REGISTRY)
from models import (
    # Trainer
    SurvivalTrainer,
    # Ensemble
    EnsembleTrainer, TrainerConfig,
    # Feature selection
    PermutationImportance, SurvivalModelWrapper,
    filter_features, filter_features_independent,
    TierThresholds, DEFAULT_THRESHOLDS, COXNET_THRESHOLDS,
)

### 1. Single trainer — string (backward compat)

In [6]:
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")

trainer = SurvivalTrainer(feature_cols=BASE_FEATURES, model_type="rsf")
trainer.cross_validate(train_df)
trainer.fit(train_df)
df_sub = trainer.make_submission(test_df)

df_sub

[auto_params] n=221  [RSF] trees=265  max_features='sqrt'  leaf=11  split=22

── Fold 1/5 [RSF] ──
   C-index@48h: 0.9423  Hybrid Score: 0.9262

── Fold 2/5 [RSF] ──
   C-index@48h: 0.9559  Hybrid Score: 0.9367

── Fold 3/5 [RSF] ──
   C-index@48h: 0.9464  Hybrid Score: 0.9412

── Fold 4/5 [RSF] ──
   C-index@48h: 0.9187  Hybrid Score: 0.9157

── Fold 5/5 [RSF] ──
   C-index@48h: 0.9135  Hybrid Score: 0.9376

[RSF] Fold scores          : [0.9262  0.9367  0.9412  0.9157  0.9376]
[RSF] Mean CV Hybrid Score : 0.9315 ± 0.0094

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.9079       0.0842       0.0802
    24h      0.9269       0.0862       0.0685  (×0.3)
    48h      0.9274       0.0880       0.0646  (×0.4)
    72h      0.9309       0.1010       0.0796  (×0.3)
------------------------------------------------
                  Hybrid Score  0.9290   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [RSF] on full training set ===
[RSF] trees=265  max_features='sqrt'  leaf=11  split=22

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=0.565  raw=0.223  cal=0.172
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=0.500  raw=0.290  cal=0.242
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=0.500  raw=0.308  cal=0.263

=== Calibration health check ===
  @12h  raw=0.223  cal=0.172  base_rate=0.222
  @24h  raw=0.290  cal=0.242  base_rate=0.285
  @48h  raw=0.308  cal=0.263  base_rate=0.299
  @72h  raw=0.385  cal=0.385  base_rate=0.312

=== Predicting on test set [RSF] ===

Submission saved → submission.csv  (95 rows)
           event_id   prob_12h   prob_24h   prob_48h   prob_72h
count  9.500000e+01  95.000000  95.000000  95.000000  95.000000
mean   5.695393e+07   0.148243   0.233104   0.255591   0.385127
std    2.329721e+07   0.233280   0.304426   0.324363   0.260833
min    1.066260e+07   0.003765   0.004735   0.006806   0.126196
25%    4.027536e+07   0.006391   0.010306   0.012542   0.170506
50%    5.480111e+07   0.011547   0.023126   0.028652   0.242068
75%    7.536942e+07   0.196128   0.531728   0.610081   0.679540
max    9.964946e+07   0.904697   0.948276   0.952047   0.952047

    event_id  prob_12h  prob_24h  prob_48h  prob_72h
0   10662602  0.010851  0.020808  0.025672  0.250247
1   13353600  0.234325  0.613990  0.669699  0.677095
2   13942327  0.009261  0.016963  0.022683  0.238819
3   16112781  0.236515  0.639422  0.690951  0.706306
4   17132808  0.769115  0.800152  0.803548  0.803548
..       ...       ...       ...       ...       ...
90  94627327  0.146561  0.163771  0.206309  0.391372
91  96570675  0.006967  0.012688  0.014440  0.175264
92  97225766  0.013203  0.027838  0.031360  0.253864
93  98446281  0.103625  0.121439  0.142705  0.335333
94  99649465  0.009701  0.016717  0.020654  0.227450

[95 rows x 5 columns]

### 2. Single trainer — inject strategy

In [10]:
# ── 2. Single trainer — inject strategy ──────────────────────
trainer = SurvivalTrainer(
    feature_cols = BASE_FEATURES,
    strategy     = RSFStrategy(n_trees=300, max_features="log2"),
)
trainer.cross_validate(train_df)
trainer.fit(train_df)

df_sub = trainer.make_submission(test_df)

df_sub

[auto_params] n=221  [RSF] trees=265  max_features='log2'  leaf=11  split=22

── Fold 1/5 [RSF] ──
   C-index@48h: 0.9423  Hybrid Score: 0.9262

── Fold 2/5 [RSF] ──
   C-index@48h: 0.9559  Hybrid Score: 0.9367

── Fold 3/5 [RSF] ──
   C-index@48h: 0.9464  Hybrid Score: 0.9412

── Fold 4/5 [RSF] ──
   C-index@48h: 0.9187  Hybrid Score: 0.9157

── Fold 5/5 [RSF] ──
   C-index@48h: 0.9135  Hybrid Score: 0.9376

[RSF] Fold scores          : [0.9262  0.9367  0.9412  0.9157  0.9376]
[RSF] Mean CV Hybrid Score : 0.9315 ± 0.0094

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.9079       0.0842       0.0802
    24h      0.9269       0.0862       0.0685  (×0.3)
    48h      0.9274       0.0880       0.0646  (×0.4)
    72h      0.9309       0.1010       0.0796  (×0.3)
------------------------------------------------
                  Hybrid Score  0.9290   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [RSF] on full training set ===
[RSF] trees=265  max_features='log2'  leaf=11  split=22

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=0.565  raw=0.223  cal=0.172
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=0.500  raw=0.290  cal=0.242
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=0.500  raw=0.308  cal=0.263

=== Calibration health check ===
  @12h  raw=0.223  cal=0.172  base_rate=0.222
  @24h  raw=0.290  cal=0.242  base_rate=0.285
  @48h  raw=0.308  cal=0.263  base_rate=0.299
  @72h  raw=0.385  cal=0.385  base_rate=0.312

=== Predicting on test set [RSF] ===

Submission saved → submission.csv  (95 rows)
           event_id   prob_12h   prob_24h   prob_48h   prob_72h
count  9.500000e+01  95.000000  95.000000  95.000000  95.000000
mean   5.695393e+07   0.148243   0.233104   0.255591   0.385127
std    2.329721e+07   0.233280   0.304426   0.324363   0.260833
min    1.066260e+07   0.003765   0.004735   0.006806   0.126196
25%    4.027536e+07   0.006391   0.010306   0.012542   0.170506
50%    5.480111e+07   0.011547   0.023126   0.028652   0.242068
75%    7.536942e+07   0.196128   0.531728   0.610081   0.679540
max    9.964946e+07   0.904697   0.948276   0.952047   0.952047

    event_id  prob_12h  prob_24h  prob_48h  prob_72h
0   10662602  0.010851  0.020808  0.025672  0.250247
1   13353600  0.234325  0.613990  0.669699  0.677095
2   13942327  0.009261  0.016963  0.022683  0.238819
3   16112781  0.236515  0.639422  0.690951  0.706306
4   17132808  0.769115  0.800152  0.803548  0.803548
..       ...       ...       ...       ...       ...
90  94627327  0.146561  0.163771  0.206309  0.391372
91  96570675  0.006967  0.012688  0.014440  0.175264
92  97225766  0.013203  0.027838  0.031360  0.253864
93  98446281  0.103625  0.121439  0.142705  0.335333
94  99649465  0.009701  0.016717  0.020654  0.227450

[95 rows x 5 columns]

### 3. Add new model strategy (XGBSEDebiasedBCE)

In [14]:
!pip install numpy>=2.0
!pip -q install xgbse

In [25]:
from xgbse import XGBSEDebiasedBCE
import numpy as np
from typing import Any
from dataclasses import field

class _XGBSurvivalFn:
    """
    Wrap one row of XGBSE predict DataFrame into a callable with .domain,
    similar to the sksurv step function interface that _survival_to_hit_probs expects.
    """
    __slots__ = ("times", "surv", "domain")

    def __init__(self, times: np.ndarray, surv: np.ndarray):
        self.times  = times
        self.surv   = np.clip(surv, 0.0, 1.0)
        self.domain = (float(times[0]), float(times[-1]))

    def __call__(self, t: float) -> float:
        return float(np.interp(t, self.times, self.surv,
                               left=self.surv[0], right=self.surv[-1]))

class XGBSEStrategy(ModelStrategy):
    """
    XGBSEDebiasedBCE survival strategy.
    Self resolve time_bins from training labels in fit().
    """

    def __init__(
        self,
        n_estimators:     int   = 200,
        learning_rate:    float = 0.05,
        max_depth:        int   = 4,
        subsample:        float = 0.8,
        colsample_bytree: float = 0.8,
        n_time_bins:      int   = 20,
    ):
        self.n_estimators     = n_estimators
        self.learning_rate    = learning_rate
        self.max_depth        = max_depth
        self.subsample        = subsample
        self.colsample_bytree = colsample_bytree
        self.n_time_bins      = n_time_bins
        self._time_bins       = None

    """
    XGBSEDebiasedBCE survival strategy.

    Self resolve time_bins from training labels in fit(),
    do not require user to specify
    """

    @property
    def name(self) -> str:
        return "XGBSE"

    # ── auto_params: scale by dataset size──────────────
    def auto_params(self, n: int) -> None:
        self.n_estimators = int(min(500, max(100, n * 1.0)))
        self.n_time_bins  = max(10, min(30, n // 10))

    # ── build: init model not fit ───────────────────────────────
    def build(self, random_state: int) -> XGBSEDebiasedBCE:
        return XGBSEDebiasedBCE(
            xgb_params={
                "n_estimators":     self.n_estimators,
                "learning_rate":    self.learning_rate,
                "max_depth":        self.max_depth,
                "subsample":        self.subsample,
                "colsample_bytree": self.colsample_bytree,
                "use_label_encoder": False,
                "eval_metric":      "logloss",
                "random_state":     random_state,
            }
        )

    # ── fit: resolve time_bins from label, then fit ─────────────────────
    def fit(self, model: XGBSEDebiasedBCE, X: np.ndarray, y: Any) -> Any:
        # y is structured array from Surv.from_dataframe
        # default field names of sksurv: y.dtype.names[0]=event, [1]=time
        event_field, time_field = y.dtype.names
        times  = y[time_field]
        events = y[event_field].astype(bool)

        # Use percentiles of event times to create bins (skip censored)
        event_times = times[events] if events.any() else times
        self._time_bins = np.unique(
            np.percentile(event_times,
                          np.linspace(0, 100, self.n_time_bins + 1))
        )

        model.fit(X, y, time_bins=self._time_bins)
        return model

    # ── predict_survival: return list callable with .domain ───────────────
    def predict_survival(self, model: XGBSEDebiasedBCE, X: np.ndarray) -> list:
        df: pd.DataFrame = model.predict(X)          # (n_samples, n_times)
        times = np.array(df.columns, dtype=float)    # time points from training

        # XGBSE returns survival P(T > t), NOT CDF
        # → use directly, do not need 1 - df
        surv_matrix = df.values                      # shape (n, T)

        return [
            _XGBSurvivalFn(times, surv_matrix[i])
            for i in range(len(surv_matrix))
        ]

    def summary_str(self) -> str:
        bins_str = (
            f"[{self._time_bins[0]:.0f}…{self._time_bins[-1]:.0f}]"
            if self._time_bins is not None else "not fit yet"
        )
        return (
            f"[XGBSE] n_est={self.n_estimators}  lr={self.learning_rate}  "
            f"depth={self.max_depth}  time_bins={len(self._time_bins) if self._time_bins is not None else '?'} {bins_str}"
        )

trainer = SurvivalTrainer(
    feature_cols=BASE_FEATURES,
    strategy=XGBSEStrategy(n_estimators=200, learning_rate=0.05),
)
trainer.cross_validate(train_df)
trainer.fit(train_df)
df_sub = trainer.make_submission(test_df)

df_sub

[auto_params] n=221  [XGBSE] n_est=221  lr=0.05  depth=4  time_bins=? not fit yet

── Fold 1/5 [XGBSE] ──
   C-index@48h: 0.8976  Hybrid Score: 0.9419

── Fold 2/5 [XGBSE] ──
   C-index@48h: 0.8978  Hybrid Score: 0.9633

── Fold 3/5 [XGBSE] ──
   C-index@48h: 0.9320  Hybrid Score: 0.9663

── Fold 4/5 [XGBSE] ──
   C-index@48h: 0.9253  Hybrid Score: 0.9703

── Fold 5/5 [XGBSE] ──
   C-index@48h: 0.8847  Hybrid Score: 0.9582

[XGBSE] Fold scores          : [0.9419  0.9633  0.9663  0.9703  0.9582]
[XGBSE] Mean CV Hybrid Score : 0.9600 ± 0.0099

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.9352       0.0632       0.0624
    24h      0.9148       0.0395       0.0302  (×0.3)
    48h      0.9108       0.0280       0.0179  (×0.4)
    72h      0.9127       0.0109       0.0047  (×0.3)
------------------------------------------------
                  Hybrid Score  0.9609   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [XGBSE] on full training set ===
[XGBSE] n_est=221  lr=0.05  depth=4  time_bins=23 [0…67]

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=0.608  raw=0.204  cal=0.187
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=0.505  raw=0.278  cal=0.283
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=0.500  raw=0.302  cal=0.301

=== Calibration health check ===
  @12h  raw=0.204  cal=0.187  base_rate=0.222
  @24h  raw=0.278  cal=0.283  base_rate=0.285
  @48h  raw=0.302  cal=0.301  base_rate=0.299
  @72h  raw=0.450  cal=0.450  base_rate=0.312

=== Predicting on test set [XGBSE] ===

Submission saved → submission.csv  (95 rows)
           event_id   prob_12h   prob_24h   prob_48h   prob_72h
count  9.500000e+01  95.000000  95.000000  95.000000  95.000000
mean   5.695393e+07   0.161290   0.248768   0.266877   0.378448
std    2.329721e+07   0.292712   0.402959   0.428671   0.364520
min    1.066260e+07   0.003109   0.003109   0.004251   0.149865
25%    4.027536e+07   0.003109   0.003109   0.004251   0.149865
50%    5.480111e+07   0.003109   0.003109   0.004251   0.149865
75%    7.536942e+07   0.176521   0.783430   0.892477   0.926549
max    9.964946e+07   0.990186   0.997660   0.998441   0.998441

    event_id  prob_12h  prob_24h  prob_48h  prob_72h
0   10662602  0.003109  0.003109  0.004251  0.149865
1   13353600  0.794852  0.986597  0.994902  0.994902
2   13942327  0.003109  0.003109  0.004251  0.149865
3   16112781  0.432540  0.788176  0.941405  0.941405
4   17132808  0.008817  0.008817  0.010598  0.197278
..       ...       ...       ...       ...       ...
90  94627327  0.005501  0.005501  0.006327  0.161239
91  96570675  0.003109  0.003109  0.004251  0.149865
92  97225766  0.003109  0.003109  0.004251  0.149865
93  98446281  0.005501  0.005501  0.006327  0.161239
94  99649465  0.003109  0.003109  0.004251  0.149865

[95 rows x 5 columns]

### 4. Ensemble

In [26]:
configs = [
    TrainerConfig("RSF",    RSFStrategy(n_trees=300),  BASE_FEATURES),
    TrainerConfig("GB",     GradBoostStrategy(),       BASE_FEATURES),
    TrainerConfig("Coxnet", CoxnetStrategy(),          BASE_FEATURES),
    TrainerConfig("CGB",    CGBStrategy(),             BASE_FEATURES),
]
ensemble = EnsembleTrainer(configs)
ensemble.cross_validate(train_df)
ensemble.optimize_weights(train_df, strategy="scipy")

# So sánh tổ hợp con (optional)
results = ensemble.compare_subsets(train_df, subset_sizes=[2, 3])
ensemble.apply_best_subset(results["best"], train_df)

ensemble.fit(train_df)
df_sub = ensemble.make_submission(test_df)

df_sub

============================================================
  EnsembleTrainer: RSF cross_validate
============================================================
[auto_params] n=221  [RSF] trees=265  max_features='sqrt'  leaf=11  split=22

── Fold 1/5 [RSF] ──
   C-index@48h: 0.9423  Hybrid Score: 0.9262

── Fold 2/5 [RSF] ──
   C-index@48h: 0.9559  Hybrid Score: 0.9367

── Fold 3/5 [RSF] ──
   C-index@48h: 0.9464  Hybrid Score: 0.9412

── Fold 4/5 [RSF] ──
   C-index@48h: 0.9187  Hybrid Score: 0.9157

── Fold 5/5 [RSF] ──
   C-index@48h: 0.9135  Hybrid Score: 0.9376

[RSF] Fold scores          : [0.9262  0.9367  0.9412  0.9157  0.9376]
[RSF] Mean CV Hybrid Score : 0.9315 ± 0.0094
============================================================
  EnsembleTrainer: GB cross_validate
============================================================
[auto_params] n=221  [GradBoost] trees=176  lr=0.05  depth=2  sub=0.75  val_frac=0.20

── Fold 1/5 [GradBoost] ──
   C-index@48h: 0.9602  Hybrid Score: 0.9672

── Fold 2/5 [GradBoost] ──
   C-index@48h: 0.9549  Hybrid Score: 0.9800

── Fold 3/5 [GradBoost] ──
   C-index@48h: 0.9485  Hybrid Score: 0.9725

── Fold 4/5 [GradBoost] ──
   C-index@48h: 0.9341  Hybrid Score: 0.9724

── Fold 5/5 [GradBoost] ──
   C-index@48h: 0.9346  Hybrid Score: 0.9718

[GradBoost] Fold scores          : [0.9672  0.9800  0.9725  0.9724  0.9718]
[GradBoost] Mean CV Hybrid Score : 0.9728 ± 0.0041
============================================================
  EnsembleTrainer: Coxnet cross_validate
============================================================
[auto_params] n=221  [Coxnet] l1_ratio=0.5  n_alphas=100  max_iter=100000

── Fold 1/5 [Coxnet] ──
   C-index@48h: 0.8738  Hybrid Score: 0.8940

── Fold 2/5 [Coxnet] ──
   C-index@48h: 0.9459  Hybrid Score: 0.9585

── Fold 3/5 [Coxnet] ──
   C-index@48h: 0.8536  Hybrid Score: 0.8724

── Fold 4/5 [Coxnet] ──
   C-index@48h: 0.5000  Hybrid Score: 0.7204

── Fold 5/5 [Coxnet] ──
   C-index@48h: 0.5000  Hybrid Score: 0.5904

[Coxnet] Fold scores          : [0.8940  0.9585  0.8724  0.7204  0.5904]
[Coxnet] Mean CV Hybrid Score : 0.8071 ± 0.1336
============================================================
  EnsembleTrainer: CGB cross_validate
============================================================
[auto_params] n=221  [CGB] n_estimators=132  lr=0.1  loss='coxph'

── Fold 1/5 [CGB] ──
   C-index@48h: 0.8946  Hybrid Score: 0.8747

── Fold 2/5 [CGB] ──
   C-index@48h: 0.8858  Hybrid Score: 0.8874

── Fold 3/5 [CGB] ──
   C-index@48h: 0.9093  Hybrid Score: 0.9003

── Fold 4/5 [CGB] ──
   C-index@48h: 0.8945  Hybrid Score: 0.8901

── Fold 5/5 [CGB] ──
   C-index@48h: 0.9069  Hybrid Score: 0.9190

[CGB] Fold scores          : [0.8747  0.8874  0.9003  0.8901  0.9190]
[CGB] Mean CV Hybrid Score : 0.8943 ± 0.0148

=== Fitting ensemble calibrator on blended OOF ===

[Ensemble] Blended OOF Hybrid Score : 0.9409
  RSF          CV Score : 0.9315  w=0.250
  GB           CV Score : 0.9728  w=0.250
  Coxnet       CV Score : 0.8071  w=0.250
  CGB          CV Score : 0.8943  w=0.250

=== optimize_weights [scipy, restarts=10] ===
  restart  1:  RSF=0.079  GB=0.917  Coxnet=0.000  CGB=0.004  score=0.9709 ←

[optimize_weights/scipy]  RSF=0.079  GB=0.917  Coxnet=0.000  CGB=0.004  score=0.9709

============================================================
  compare_subsets: 10 combinations, sizes=[2, 3]
============================================================
  [  1/10] RSF+GB                          RSF=0.304  GB=0.696  score=0.9701
  [  2/10] RSF+Coxnet                      RSF=0.923  Coxnet=0.077  score=0.9290
  [  3/10] RSF+CGB                         RSF=0.678  CGB=0.322  score=0.9197
  [  4/10] GB+Coxnet                       GB=0.965  Coxnet=0.035  score=0.9702
  [  5/10] GB+CGB                          GB=0.828  CGB=0.172  score=0.9707
  [  6/10] Coxnet+CGB                      Coxnet=0.149  CGB=0.851  score=0.8936
  [  7/10] RSF+GB+Coxnet                   RSF=0.297  GB=0.678  Coxnet=0.025  score=0.9701
  [  8/10] RSF+GB+CGB                      RSF=0.266  GB=0.608  CGB=0.126  score=0.9686
  [  9/10] RSF+Coxnet+CGB                  RSF=0.642  Coxnet=0.053  CGB=0.305  score=0.9208
  [ 10/10] GB+Coxnet+CGB                   GB=0.804  Coxnet=0.029  CGB=0.167  score=0.9709

────────────────────────────────────────────────────────────
  TOP 5 combinations:
────────────────────────────────────────────────────────────
  #1  GB+Coxnet+CGB                   GB=0.804  Coxnet=0.029  CGB=0.167  score=0.9709
  #2  GB+CGB                          GB=0.828  CGB=0.172  score=0.9707
  #3  GB+Coxnet                       GB=0.965  Coxnet=0.035  score=0.9702
  #4  RSF+GB                          RSF=0.304  GB=0.696  score=0.9701
  #5  RSF+GB+Coxnet                   RSF=0.297  GB=0.678  Coxnet=0.025  score=0.9701

[apply_best_subset] Dropping models: {'RSF'}
[apply_best_subset] Active: ['GB', 'Coxnet', 'CGB']
  weights: (0.8035860035476013, 0.029244865123604417, 0.1671691313287942)
  score  : 0.9709

============================================================
  EnsembleTrainer: GB fit
============================================================

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.9429       0.0527       0.0516
    24h      0.9385       0.0317       0.0308  (×0.3)
    48h      0.9453       0.0191       0.0160  (×0.4)
    72h      0.9459       0.0026       0.0011  (×0.3)
------------------------------------------------
                  Hybrid Score  0.9724   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [GradBoost] on full training set ===
[GradBoost] trees=176  lr=0.05  depth=2  sub=0.75  val_frac=0.20

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=0.826  raw=0.252  cal=0.246
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=0.819  raw=0.325  cal=0.313
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=0.567  raw=0.342  cal=0.313

=== Calibration health check ===
  @12h  raw=0.252  cal=0.246  base_rate=0.222
  @24h  raw=0.325  cal=0.313  base_rate=0.285
  @48h  raw=0.342  cal=0.313  base_rate=0.299
  @72h  raw=0.383  cal=0.383  base_rate=0.312

============================================================
  EnsembleTrainer: Coxnet fit
============================================================

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.7885       0.1453       0.1273
    24h      0.7889       0.1695       0.1418  (×0.3)
    48h      0.7856       0.2100       0.1669  (×0.4)
    72h      0.8250       0.2408       0.1656  (×0.3)
------------------------------------------------
                  Hybrid Score  0.8244   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [Coxnet] on full training set ===
[Coxnet] l1_ratio=0.5  n_alphas=100  max_iter=100000

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=6.976  raw=0.121  cal=0.237
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=8.411  raw=0.163  cal=0.276
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=10.000  raw=0.179  cal=0.306

=== Calibration health check ===
  @12h  raw=0.121  cal=0.237  base_rate=0.222
  @24h  raw=0.163  cal=0.276  base_rate=0.285
  @48h  raw=0.179  cal=0.306  base_rate=0.299
  @72h  raw=0.290  cal=0.290  base_rate=0.312

============================================================
  EnsembleTrainer: CGB fit
============================================================

=== OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.8831       0.1000       0.0951
    24h      0.8837       0.1271       0.1232  (×0.3)
    48h      0.8816       0.1330       0.1273  (×0.4)
    72h      0.8581       0.0708       0.0674  (×0.3)
------------------------------------------------
                  Hybrid Score  0.8888   = 0.3×C@48h + 0.7×(1−WBS)

=== Retraining [CGB] on full training set ===
[CGB] n_estimators=132  lr=0.1  loss='coxph'

=== Calibration diagnostics ===
  @12h  n_pos= 49 n_neg=166 excl=  6  base=0.228  T=0.630  raw=0.248  cal=0.195
  @24h  n_pos= 63 n_neg=133 excl= 25  base=0.321  T=0.634  raw=0.327  cal=0.284
  @48h  n_pos= 66 n_neg=100 excl= 55  base=0.398  T=0.650  raw=0.348  cal=0.311

=== Calibration health check ===
  @12h  raw=0.248  cal=0.195  base_rate=0.222
  @24h  raw=0.327  cal=0.284  base_rate=0.285
  @48h  raw=0.348  cal=0.311  base_rate=0.299
  @72h  raw=0.541  cal=0.541  base_rate=0.312

=== EnsembleTrainer: Refitting ensemble calibrator ===

=== EnsembleTrainer: Blended OOF evaluation ===

 Horizon    C-index    Brier raw    Brier cal
------------------------------------------------
    12h      0.9414       0.0526       0.0520
    24h      0.9400       0.0361       0.0291  (×0.3)
    48h      0.9409       0.0263       0.0168  (×0.4)
    72h      0.9439       0.0066       0.0026  (×0.3)
------------------------------------------------
                  Hybrid Score  0.9709   = 0.3×C@48h + 0.7×(1−WBS)

=== EnsembleTrainer: Predicting on test set ===
  [GB] predicting...
  [Coxnet] predicting...
  [CGB] predicting...

Submission saved → submission.csv  (95 rows)
       prob_12h  prob_24h  prob_48h  prob_72h
count   95.0000   95.0000   95.0000   95.0000
mean     0.2072    0.2790    0.2867    0.4042
std      0.3318    0.4144    0.4252    0.3608
min      0.0018    0.0032    0.0032    0.0942
25%      0.0043    0.0069    0.0069    0.1492
50%      0.0091    0.0140    0.0140    0.1988
75%      0.4008    0.7968    0.8516    0.8994
max      0.9982    0.9999    1.0000    1.0000

    event_id  prob_12h  prob_24h  prob_48h  prob_72h
0   10662602  0.005358  0.008492  0.008492  0.164179
1   13353600  0.757028  0.959969  0.974555  0.974555
2   13942327  0.009147  0.013995  0.013995  0.198850
3   16112781  0.717372  0.951201  0.969054  0.969054
4   17132808  0.037468  0.053109  0.053109  0.273314
..       ...       ...       ...       ...       ...
90  94627327  0.024769  0.037004  0.037004  0.260528
91  96570675  0.008863  0.013725  0.013725  0.198231
92  97225766  0.004764  0.007686  0.007686  0.156893
93  98446281  0.011706  0.019200  0.019200  0.227639
94  99649465  0.005420  0.008699  0.008699  0.165958

[95 rows x 5 columns]

### 5. Feature selection — string (backward compat)

In [4]:
train_df = pd.read_csv('data/train.csv')
enriched_train_df = enrich_features(pd.read_csv('data/train.csv'))

enriched_features = list(set(enriched_train_df.columns) - set(train_df.columns))
enriched_features

['momentum_threat',
 'log1p_dist_min',
 'eta_radial',
 'area_speed_ratio',
 'hour_sin',
 'dist_change_norm',
 'radial_bearing_threat',
 'closing_neg',
 'log1p_reliable_slope',
 'log1p_speed_consistency',
 'eta_combined',
 'linear_eta_ci',
 'log1p_centroid_disp',
 'log1p_projected',
 'eta_projected',
 'eta_closing',
 'area_radial_threat',
 'dist_cv',
 'reliable_accel',
 'hour_cos',
 'is_approaching',
 'reliable_eta_ci',
 'eta_bearing_adjusted',
 'directional_growth',
 'dt_x_alignment',
 'log1p_dist_change',
 'log1p_dist_slope',
 'log1p_threat_alignment',
 'log1p_dist_std',
 'eta_along_track',
 'growth_pressure',
 'log1p_radial_growth_rate',
 'log1p_radial_growth',
 'reliable_slope',
 'log1p_centroid_speed',
 'aligned_along_speed',
 'relative_accel',
 'bearing_threat_factor',
 'closing_pos',
 'dist_per_area',
 'log1p_closing_speed',
 'is_high_wind_hour',
 'eta_aligned_along',
 'speed_consistency',
 'alignment_x_nperim',
 'threat_alignment',
 'cross_track_ratio']

In [5]:
remove_feature = ['dist_min_ci_0_5h']
base_features = [f for f in BASE_FEATURES if f not in remove_feature]
base_features

['num_perimeters_0_5h',
 'dt_first_last_0_5h',
 'low_temporal_resolution_0_5h',
 'area_first_ha',
 'area_growth_abs_0_5h',
 'area_growth_rel_0_5h',
 'area_growth_rate_ha_per_h',
 'log1p_area_first',
 'log1p_growth',
 'log_area_ratio_0_5h',
 'relative_growth_0_5h',
 'radial_growth_m',
 'radial_growth_rate_m_per_h',
 'centroid_displacement_m',
 'centroid_speed_m_per_h',
 'spread_bearing_deg',
 'spread_bearing_sin',
 'spread_bearing_cos',
 'dist_std_ci_0_5h',
 'dist_change_ci_0_5h',
 'dist_slope_ci_0_5h',
 'closing_speed_m_per_h',
 'closing_speed_abs_m_per_h',
 'projected_advance_m',
 'dist_accel_m_per_h2',
 'dist_fit_r2_0_5h',
 'alignment_cos',
 'alignment_abs',
 'cross_track_component',
 'along_track_speed',
 'event_start_hour',
 'event_start_dayofweek',
 'event_start_month']

In [6]:
result = filter_features(
    enriched_train_df,
    base_features,
    enriched_features,
    model_type="rsf",
    n_repeats=10,
)
survival_features = result["survival_features"]  # TIER1 + TIER2
survival_features

Features — Base: 33 | Enriched: 47 | Total: 80
  Fold 1 | RSF baseline: 0.9642
  Fold 2 | RSF baseline: 0.9367
  Fold 3 | RSF baseline: 0.9643

============================================================================
  Permutation Importance [RSF]
============================================================================
#    Feature                              Importance   FoldStd  Type       Mark
============================================================================
1    log1p_dist_min                          0.01879   0.00281  enriched   ★
2    eta_along_track                         0.01580   0.00154  enriched   ★
3    eta_projected                           0.01279   0.00125  enriched   ★
4    eta_closing                             0.01277   0.00157  enriched   ★
5    eta_aligned_along                       0.01232   0.00212  enriched   ★
6    eta_radial                              0.01140   0.00453  enriched   ★
7    eta_combined                            0.00955   0.00336  enriched   ★
8    eta_bearing_adjusted                    0.00896   0.00496  enriched   ★
9    alignment_x_nperim                      0.00130   0.00146  enriched   +
10   dt_first_last_0_5h                      0.00112   0.00045  base       +
11   alignment_abs                           0.00082   0.00068  base       +
12   dt_x_alignment                          0.00081   0.00003  enriched   +
13   dist_per_area                           0.00059   0.00038  enriched   +
14   low_temporal_resolution_0_5h            0.00051   0.00073  base       +
15   is_high_wind_hour                       0.00041   0.00101  enriched   +
16   bearing_threat_factor                   0.00033   0.00029  enriched   +
17   event_start_month                       0.00023   0.00041  base       +
18   spread_bearing_cos                      0.00021   0.00040  base       +
19   directional_growth                      0.00018   0.00016  enriched   +
20   alignment_cos                           0.00011   0.00042  base       +
21   area_growth_rel_0_5h                    0.00009   0.00013  base       +
22   spread_bearing_deg                      0.00009   0.00015  base       +
23   centroid_speed_m_per_h                  0.00008   0.00017  base       +
24   relative_growth_0_5h                    0.00007   0.00011  base       +
25   num_perimeters_0_5h                     0.00007   0.00028  base       +
26   area_first_ha                           0.00006   0.00074  base       +
27   cross_track_ratio                       0.00005   0.00009  enriched   +
28   speed_consistency                       0.00005   0.00010  enriched   +
29   log1p_speed_consistency                 0.00004   0.00006  enriched   +
30   event_start_dayofweek                   0.00003   0.00027  base       +
31   log1p_radial_growth_rate                0.00002   0.00003  enriched   +
32   momentum_threat                         0.00002   0.00005  enriched   +
33   area_growth_rate_ha_per_h               0.00001   0.00002  base       +
34   log_area_ratio_0_5h                     0.00000   0.00001  base       +
35   log1p_projected                         0.00000   0.00000  enriched   ✗
36   log1p_dist_std                          0.00000   0.00000  enriched   ✗
37   log1p_radial_growth                     0.00000   0.00000  enriched   ✗
38   log1p_dist_slope                        0.00000   0.00000  enriched   ✗
39   radial_growth_m                         0.00000   0.00000  base       ✗
40   reliable_slope                          0.00000   0.00000  enriched   ✗
41   log1p_reliable_slope                    0.00000   0.00000  enriched   ✗
42   radial_bearing_threat                   0.00000   0.00000  enriched   ✗
43   reliable_eta_ci                         0.00000   0.00000  enriched   ✗
44   reliable_accel                          0.00000   0.00000  enriched   ✗
45   log1p_threat_alignment                  0.00000   0.00000  enriched   ✗
46   relative_accel                          0.00000   0.00000  enriched   ✗
47   log1p_closing_speed                     0.00000   0.00000  enriched   ✗
48   projected_advance_m                     0.00000   0.00000  base       ✗
49   log1p_dist_change                       0.00000   0.00000  enriched   ✗
50   aligned_along_speed                     0.00000   0.00000  enriched   ✗
51   dist_change_ci_0_5h                     0.00000   0.00000  base       ✗
52   dist_fit_r2_0_5h                        0.00000   0.00000  base       ✗
53   along_track_speed                       0.00000   0.00000  base       ✗
54   area_radial_threat                      0.00000   0.00000  enriched   ✗
55   closing_neg                             0.00000   0.00000  enriched   ✗
56   closing_pos                             0.00000   0.00000  enriched   ✗
57   closing_speed_abs_m_per_h               0.00000   0.00000  base       ✗
58   closing_speed_m_per_h                   0.00000   0.00000  base       ✗
59   dist_accel_m_per_h2                     0.00000   0.00000  base       ✗
60   log1p_centroid_disp                     0.00000   0.00000  enriched   ✗
61   dist_change_norm                        0.00000   0.00000  enriched   ✗
62   dist_cv                                 0.00000   0.00000  enriched   ✗
63   threat_alignment                        0.00000   0.00000  enriched   ✗
64   dist_slope_ci_0_5h                      0.00000   0.00000  base       ✗
65   dist_std_ci_0_5h                        0.00000   0.00000  base       ✗
66   linear_eta_ci                           0.00000   0.00000  enriched   ✗
67   is_approaching                          0.00000   0.00000  enriched   ✗
68   cross_track_component                  -0.00001   0.00001  base       ✗
69   growth_pressure                        -0.00001   0.00002  enriched   ✗
70   centroid_displacement_m                -0.00001   0.00030  base       ✗
71   log1p_centroid_speed                   -0.00002   0.00004  enriched   ✗
72   spread_bearing_sin                     -0.00003   0.00005  base       ✗
73   radial_growth_rate_m_per_h             -0.00005   0.00011  base       ✗
74   area_growth_abs_0_5h                   -0.00006   0.00012  base       ✗
75   log1p_growth                           -0.00007   0.00011  base       ✗
76   event_start_hour                       -0.00014   0.00048  base       ✗
77   log1p_area_first                       -0.00015   0.00114  base       ✗
78   area_speed_ratio                       -0.00030   0.00068  enriched   ✗
79   hour_sin                               -0.00037   0.00052  enriched   ✗
80   hour_cos                               -0.00042   0.00101  enriched   ✗
============================================================================

── Summary by type ──
  base      : 15/33 positive | top-3: ['dt_first_last_0_5h', 'alignment_abs', 'low_temporal_resolution_0_5h']
  enriched  : 19/47 positive | top-3: ['log1p_dist_min', 'eta_along_track', 'eta_projected']

TIER1 (8):
  log1p_dist_min                      imp= 0.01879  std= 0.00281  ratio=0.1x
  eta_along_track                     imp= 0.01580  std= 0.00154  ratio=0.1x
  eta_projected                       imp= 0.01279  std= 0.00125  ratio=0.1x
  eta_closing                         imp= 0.01277  std= 0.00157  ratio=0.1x
  eta_aligned_along                   imp= 0.01232  std= 0.00212  ratio=0.2x
  eta_radial                          imp= 0.01140  std= 0.00453  ratio=0.4x
  eta_combined                        imp= 0.00955  std= 0.00336  ratio=0.4x
  eta_bearing_adjusted                imp= 0.00896  std= 0.00496  ratio=0.6x

TIER2 (6):
  alignment_x_nperim                  imp= 0.00130  std= 0.00146  ratio=1.1x
  dt_first_last_0_5h                  imp= 0.00112  std= 0.00045  ratio=0.4x
  alignment_abs                       imp= 0.00082  std= 0.00068  ratio=0.8x
  dt_x_alignment                      imp= 0.00081  std= 0.00003  ratio=0.0x
  dist_per_area                       imp= 0.00059  std= 0.00038  ratio=0.6x
  low_temporal_resolution_0_5h        imp= 0.00051  std= 0.00073  ratio=1.4x

TIER3 (20):
  is_high_wind_hour                   imp= 0.00041  std= 0.00101  ratio=2.4x
  bearing_threat_factor               imp= 0.00033  std= 0.00029  ratio=0.9x
  event_start_month                   imp= 0.00023  std= 0.00041  ratio=1.8x
  spread_bearing_cos                  imp= 0.00021  std= 0.00040  ratio=1.9x
  directional_growth                  imp= 0.00018  std= 0.00016  ratio=0.9x
  alignment_cos                       imp= 0.00011  std= 0.00042  ratio=3.7x
  area_growth_rel_0_5h                imp= 0.00009  std= 0.00013  ratio=1.5x
  spread_bearing_deg                  imp= 0.00009  std= 0.00015  ratio=1.7x
  centroid_speed_m_per_h              imp= 0.00008  std= 0.00017  ratio=2.1x
  relative_growth_0_5h                imp= 0.00007  std= 0.00011  ratio=1.6x
  num_perimeters_0_5h                 imp= 0.00007  std= 0.00028  ratio=4.3x
  area_first_ha                       imp= 0.00006  std= 0.00074  ratio=11.4x
  cross_track_ratio                   imp= 0.00005  std= 0.00009  ratio=1.6x
  speed_consistency                   imp= 0.00005  std= 0.00010  ratio=2.3x
  log1p_speed_consistency             imp= 0.00004  std= 0.00006  ratio=1.6x
  event_start_dayofweek               imp= 0.00003  std= 0.00027  ratio=9.9x
  log1p_radial_growth_rate            imp= 0.00002  std= 0.00003  ratio=1.7x
  momentum_threat                     imp= 0.00002  std= 0.00005  ratio=2.8x
  area_growth_rate_ha_per_h           imp= 0.00001  std= 0.00002  ratio=1.7x
  log_area_ratio_0_5h                 imp= 0.00000  std= 0.00001  ratio=1.7x

DROP (46):
  log1p_projected                     imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_std                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_radial_growth                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_slope                    imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_growth_m                     imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_slope                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_reliable_slope                imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_bearing_threat               imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_eta_ci                     imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_threat_alignment              imp= 0.00000  std= 0.00000  ratio=0.0x
  relative_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_closing_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  projected_advance_m                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_change                   imp= 0.00000  std= 0.00000  ratio=0.0x
  aligned_along_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_ci_0_5h                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_fit_r2_0_5h                    imp= 0.00000  std= 0.00000  ratio=0.0x
  along_track_speed                   imp= 0.00000  std= 0.00000  ratio=0.0x
  area_radial_threat                  imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_neg                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_pos                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_abs_m_per_h           imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_m_per_h               imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_accel_m_per_h2                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_centroid_disp                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_norm                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_cv                             imp= 0.00000  std= 0.00000  ratio=0.0x
  threat_alignment                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_slope_ci_0_5h                  imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_std_ci_0_5h                    imp= 0.00000  std= 0.00000  ratio=0.0x
  linear_eta_ci                       imp= 0.00000  std= 0.00000  ratio=0.0x
  is_approaching                      imp= 0.00000  std= 0.00000  ratio=0.0x
  cross_track_component               imp=-0.00001  std= 0.00001  ratio=-1.7x
  growth_pressure                     imp=-0.00001  std= 0.00002  ratio=-1.7x
  centroid_displacement_m             imp=-0.00001  std= 0.00030  ratio=-20.1x
  log1p_centroid_speed                imp=-0.00002  std= 0.00004  ratio=-1.6x
  spread_bearing_sin                  imp=-0.00003  std= 0.00005  ratio=-2.0x
  radial_growth_rate_m_per_h          imp=-0.00005  std= 0.00011  ratio=-2.1x
  area_growth_abs_0_5h                imp=-0.00006  std= 0.00012  ratio=-1.8x
  log1p_growth                        imp=-0.00007  std= 0.00011  ratio=-1.7x
  event_start_hour                    imp=-0.00014  std= 0.00048  ratio=-3.4x
  log1p_area_first                    imp=-0.00015  std= 0.00114  ratio=-7.7x
  area_speed_ratio                    imp=-0.00030  std= 0.00068  ratio=-2.2x
  hour_sin                            imp=-0.00037  std= 0.00052  ratio=-1.4x
  hour_cos                            imp=-0.00042  std= 0.00101  ratio=-2.4x

Survival features (TIER1 + TIER2): 14
['log1p_dist_min', 'eta_along_track', 'eta_projected', 'eta_closing', 'eta_aligned_along', 'eta_radial', 'eta_combined', 'eta_bearing_adjusted', 'alignment_x_nperim', 'dt_first_last_0_5h', 'alignment_abs', 'dt_x_alignment', 'dist_per_area', 'low_temporal_resolution_0_5h']

['log1p_dist_min',
 'eta_along_track',
 'eta_projected',
 'eta_closing',
 'eta_aligned_along',
 'eta_radial',
 'eta_combined',
 'eta_bearing_adjusted',
 'alignment_x_nperim',
 'dt_first_last_0_5h',
 'alignment_abs',
 'dt_x_alignment',
 'dist_per_area',
 'low_temporal_resolution_0_5h']

In [9]:
# Multi-model
multi = filter_features_independent(
    enriched_train_df,
    base_features,
    enriched_features,
    n_repeats=10,
)
# → {"rsf": [...], "gradboost": [...], "coxnet": [...], "cgb": [...]}
multi

======================================================================
  Step 1/4: RSF Permutation Importance  [PRIMARY]
======================================================================

Features — Base: 33 | Enriched: 47 | Total: 80
  Fold 1 | RSF baseline: 0.9642
  Fold 2 | RSF baseline: 0.9367
  Fold 3 | RSF baseline: 0.9643

============================================================================
  Permutation Importance [RSF]
============================================================================
#    Feature                              Importance   FoldStd  Type       Mark
============================================================================
1    log1p_dist_min                          0.01879   0.00281  enriched   ★
2    eta_along_track                         0.01580   0.00154  enriched   ★
3    eta_projected                           0.01279   0.00125  enriched   ★
4    eta_closing                             0.01277   0.00157  enriched   ★
5    eta_aligned_along                       0.01232   0.00212  enriched   ★
6    eta_radial                              0.01140   0.00453  enriched   ★
7    eta_combined                            0.00955   0.00336  enriched   ★
8    eta_bearing_adjusted                    0.00896   0.00496  enriched   ★
9    alignment_x_nperim                      0.00130   0.00146  enriched   +
10   dt_first_last_0_5h                      0.00112   0.00045  base       +
11   alignment_abs                           0.00082   0.00068  base       +
12   dt_x_alignment                          0.00081   0.00003  enriched   +
13   dist_per_area                           0.00059   0.00038  enriched   +
14   low_temporal_resolution_0_5h            0.00051   0.00073  base       +
15   is_high_wind_hour                       0.00041   0.00101  enriched   +
16   bearing_threat_factor                   0.00033   0.00029  enriched   +
17   event_start_month                       0.00023   0.00041  base       +
18   spread_bearing_cos                      0.00021   0.00040  base       +
19   directional_growth                      0.00018   0.00016  enriched   +
20   alignment_cos                           0.00011   0.00042  base       +
21   area_growth_rel_0_5h                    0.00009   0.00013  base       +
22   spread_bearing_deg                      0.00009   0.00015  base       +
23   centroid_speed_m_per_h                  0.00008   0.00017  base       +
24   relative_growth_0_5h                    0.00007   0.00011  base       +
25   num_perimeters_0_5h                     0.00007   0.00028  base       +
26   area_first_ha                           0.00006   0.00074  base       +
27   cross_track_ratio                       0.00005   0.00009  enriched   +
28   speed_consistency                       0.00005   0.00010  enriched   +
29   log1p_speed_consistency                 0.00004   0.00006  enriched   +
30   event_start_dayofweek                   0.00003   0.00027  base       +
31   log1p_radial_growth_rate                0.00002   0.00003  enriched   +
32   momentum_threat                         0.00002   0.00005  enriched   +
33   area_growth_rate_ha_per_h               0.00001   0.00002  base       +
34   log_area_ratio_0_5h                     0.00000   0.00001  base       +
35   log1p_projected                         0.00000   0.00000  enriched   ✗
36   log1p_dist_std                          0.00000   0.00000  enriched   ✗
37   log1p_radial_growth                     0.00000   0.00000  enriched   ✗
38   log1p_dist_slope                        0.00000   0.00000  enriched   ✗
39   radial_growth_m                         0.00000   0.00000  base       ✗
40   reliable_slope                          0.00000   0.00000  enriched   ✗
41   log1p_reliable_slope                    0.00000   0.00000  enriched   ✗
42   radial_bearing_threat                   0.00000   0.00000  enriched   ✗
43   reliable_eta_ci                         0.00000   0.00000  enriched   ✗
44   reliable_accel                          0.00000   0.00000  enriched   ✗
45   log1p_threat_alignment                  0.00000   0.00000  enriched   ✗
46   relative_accel                          0.00000   0.00000  enriched   ✗
47   log1p_closing_speed                     0.00000   0.00000  enriched   ✗
48   projected_advance_m                     0.00000   0.00000  base       ✗
49   log1p_dist_change                       0.00000   0.00000  enriched   ✗
50   aligned_along_speed                     0.00000   0.00000  enriched   ✗
51   dist_change_ci_0_5h                     0.00000   0.00000  base       ✗
52   dist_fit_r2_0_5h                        0.00000   0.00000  base       ✗
53   along_track_speed                       0.00000   0.00000  base       ✗
54   area_radial_threat                      0.00000   0.00000  enriched   ✗
55   closing_neg                             0.00000   0.00000  enriched   ✗
56   closing_pos                             0.00000   0.00000  enriched   ✗
57   closing_speed_abs_m_per_h               0.00000   0.00000  base       ✗
58   closing_speed_m_per_h                   0.00000   0.00000  base       ✗
59   dist_accel_m_per_h2                     0.00000   0.00000  base       ✗
60   log1p_centroid_disp                     0.00000   0.00000  enriched   ✗
61   dist_change_norm                        0.00000   0.00000  enriched   ✗
62   dist_cv                                 0.00000   0.00000  enriched   ✗
63   threat_alignment                        0.00000   0.00000  enriched   ✗
64   dist_slope_ci_0_5h                      0.00000   0.00000  base       ✗
65   dist_std_ci_0_5h                        0.00000   0.00000  base       ✗
66   linear_eta_ci                           0.00000   0.00000  enriched   ✗
67   is_approaching                          0.00000   0.00000  enriched   ✗
68   cross_track_component                  -0.00001   0.00001  base       ✗
69   growth_pressure                        -0.00001   0.00002  enriched   ✗
70   centroid_displacement_m                -0.00001   0.00030  base       ✗
71   log1p_centroid_speed                   -0.00002   0.00004  enriched   ✗
72   spread_bearing_sin                     -0.00003   0.00005  base       ✗
73   radial_growth_rate_m_per_h             -0.00005   0.00011  base       ✗
74   area_growth_abs_0_5h                   -0.00006   0.00012  base       ✗
75   log1p_growth                           -0.00007   0.00011  base       ✗
76   event_start_hour                       -0.00014   0.00048  base       ✗
77   log1p_area_first                       -0.00015   0.00114  base       ✗
78   area_speed_ratio                       -0.00030   0.00068  enriched   ✗
79   hour_sin                               -0.00037   0.00052  enriched   ✗
80   hour_cos                               -0.00042   0.00101  enriched   ✗
============================================================================

── Summary by type ──
  base      : 15/33 positive | top-3: ['dt_first_last_0_5h', 'alignment_abs', 'low_temporal_resolution_0_5h']
  enriched  : 19/47 positive | top-3: ['log1p_dist_min', 'eta_along_track', 'eta_projected']

Saved → permutation_importance_rsf.csv

TIER1 (8):
  log1p_dist_min                      imp= 0.01879  std= 0.00281  ratio=0.1x
  eta_along_track                     imp= 0.01580  std= 0.00154  ratio=0.1x
  eta_projected                       imp= 0.01279  std= 0.00125  ratio=0.1x
  eta_closing                         imp= 0.01277  std= 0.00157  ratio=0.1x
  eta_aligned_along                   imp= 0.01232  std= 0.00212  ratio=0.2x
  eta_radial                          imp= 0.01140  std= 0.00453  ratio=0.4x
  eta_combined                        imp= 0.00955  std= 0.00336  ratio=0.4x
  eta_bearing_adjusted                imp= 0.00896  std= 0.00496  ratio=0.6x

TIER2 (6):
  alignment_x_nperim                  imp= 0.00130  std= 0.00146  ratio=1.1x
  dt_first_last_0_5h                  imp= 0.00112  std= 0.00045  ratio=0.4x
  alignment_abs                       imp= 0.00082  std= 0.00068  ratio=0.8x
  dt_x_alignment                      imp= 0.00081  std= 0.00003  ratio=0.0x
  dist_per_area                       imp= 0.00059  std= 0.00038  ratio=0.6x
  low_temporal_resolution_0_5h        imp= 0.00051  std= 0.00073  ratio=1.4x

TIER3 (20):
  is_high_wind_hour                   imp= 0.00041  std= 0.00101  ratio=2.4x
  bearing_threat_factor               imp= 0.00033  std= 0.00029  ratio=0.9x
  event_start_month                   imp= 0.00023  std= 0.00041  ratio=1.8x
  spread_bearing_cos                  imp= 0.00021  std= 0.00040  ratio=1.9x
  directional_growth                  imp= 0.00018  std= 0.00016  ratio=0.9x
  alignment_cos                       imp= 0.00011  std= 0.00042  ratio=3.7x
  area_growth_rel_0_5h                imp= 0.00009  std= 0.00013  ratio=1.5x
  spread_bearing_deg                  imp= 0.00009  std= 0.00015  ratio=1.7x
  centroid_speed_m_per_h              imp= 0.00008  std= 0.00017  ratio=2.1x
  relative_growth_0_5h                imp= 0.00007  std= 0.00011  ratio=1.6x
  num_perimeters_0_5h                 imp= 0.00007  std= 0.00028  ratio=4.3x
  area_first_ha                       imp= 0.00006  std= 0.00074  ratio=11.4x
  cross_track_ratio                   imp= 0.00005  std= 0.00009  ratio=1.6x
  speed_consistency                   imp= 0.00005  std= 0.00010  ratio=2.3x
  log1p_speed_consistency             imp= 0.00004  std= 0.00006  ratio=1.6x
  event_start_dayofweek               imp= 0.00003  std= 0.00027  ratio=9.9x
  log1p_radial_growth_rate            imp= 0.00002  std= 0.00003  ratio=1.7x
  momentum_threat                     imp= 0.00002  std= 0.00005  ratio=2.8x
  area_growth_rate_ha_per_h           imp= 0.00001  std= 0.00002  ratio=1.7x
  log_area_ratio_0_5h                 imp= 0.00000  std= 0.00001  ratio=1.7x

DROP (46):
  log1p_projected                     imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_std                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_radial_growth                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_slope                    imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_growth_m                     imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_slope                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_reliable_slope                imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_bearing_threat               imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_eta_ci                     imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_threat_alignment              imp= 0.00000  std= 0.00000  ratio=0.0x
  relative_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_closing_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  projected_advance_m                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_change                   imp= 0.00000  std= 0.00000  ratio=0.0x
  aligned_along_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_ci_0_5h                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_fit_r2_0_5h                    imp= 0.00000  std= 0.00000  ratio=0.0x
  along_track_speed                   imp= 0.00000  std= 0.00000  ratio=0.0x
  area_radial_threat                  imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_neg                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_pos                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_abs_m_per_h           imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_m_per_h               imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_accel_m_per_h2                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_centroid_disp                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_norm                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_cv                             imp= 0.00000  std= 0.00000  ratio=0.0x
  threat_alignment                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_slope_ci_0_5h                  imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_std_ci_0_5h                    imp= 0.00000  std= 0.00000  ratio=0.0x
  linear_eta_ci                       imp= 0.00000  std= 0.00000  ratio=0.0x
  is_approaching                      imp= 0.00000  std= 0.00000  ratio=0.0x
  cross_track_component               imp=-0.00001  std= 0.00001  ratio=-1.7x
  growth_pressure                     imp=-0.00001  std= 0.00002  ratio=-1.7x
  centroid_displacement_m             imp=-0.00001  std= 0.00030  ratio=-20.1x
  log1p_centroid_speed                imp=-0.00002  std= 0.00004  ratio=-1.6x
  spread_bearing_sin                  imp=-0.00003  std= 0.00005  ratio=-2.0x
  radial_growth_rate_m_per_h          imp=-0.00005  std= 0.00011  ratio=-2.1x
  area_growth_abs_0_5h                imp=-0.00006  std= 0.00012  ratio=-1.8x
  log1p_growth                        imp=-0.00007  std= 0.00011  ratio=-1.7x
  event_start_hour                    imp=-0.00014  std= 0.00048  ratio=-3.4x
  log1p_area_first                    imp=-0.00015  std= 0.00114  ratio=-7.7x
  area_speed_ratio                    imp=-0.00030  std= 0.00068  ratio=-2.2x
  hour_sin                            imp=-0.00037  std= 0.00052  ratio=-1.4x
  hour_cos                            imp=-0.00042  std= 0.00101  ratio=-2.4x

Survival features (TIER1 + TIER2): 14
['log1p_dist_min', 'eta_along_track', 'eta_projected', 'eta_closing', 'eta_aligned_along', 'eta_radial', 'eta_combined', 'eta_bearing_adjusted', 'alignment_x_nperim', 'dt_first_last_0_5h', 'alignment_abs', 'dt_x_alignment', 'dist_per_area', 'low_temporal_resolution_0_5h']

======================================================================
  Step 2/4: GradBoost Permutation Importance  [SUPPORT]
======================================================================

Features — Base: 33 | Enriched: 47 | Total: 80
  Fold 1 | GradBoost baseline: 0.9599
  Fold 2 | GradBoost baseline: 0.9358
  Fold 3 | GradBoost baseline: 0.9684

============================================================================
  Permutation Importance [GRADBOOST]
============================================================================
#    Feature                              Importance   FoldStd  Type       Mark
============================================================================
1    log1p_dist_min                          0.18365   0.13030  enriched   ★
2    eta_closing                             0.00438   0.00539  enriched   +
3    dist_per_area                           0.00191   0.00063  enriched   +
4    eta_aligned_along                       0.00173   0.00289  enriched   +
5    dt_first_last_0_5h                      0.00170   0.00149  base       +
6    eta_projected                           0.00158   0.00254  enriched   +
7    eta_along_track                         0.00130   0.00147  enriched   +
8    event_start_month                       0.00024   0.00040  base       +
9    event_start_dayofweek                   0.00001   0.00024  base       +
10   log1p_projected                         0.00000   0.00000  enriched   ✗
11   log1p_growth                            0.00000   0.00000  base       ✗
12   log1p_dist_std                          0.00000   0.00000  enriched   ✗
13   log1p_dist_slope                        0.00000   0.00000  enriched   ✗
14   log1p_closing_speed                     0.00000   0.00000  enriched   ✗
15   log1p_dist_change                       0.00000   0.00000  enriched   ✗
16   growth_pressure                         0.00000   0.00000  enriched   ✗
17   log1p_centroid_speed                    0.00000   0.00000  enriched   ✗
18   log1p_centroid_disp                     0.00000   0.00000  enriched   ✗
19   linear_eta_ci                           0.00000   0.00000  enriched   ✗
20   log1p_radial_growth                     0.00000   0.00000  enriched   ✗
21   log1p_radial_growth_rate                0.00000   0.00000  enriched   ✗
22   log1p_reliable_slope                    0.00000   0.00000  enriched   ✗
23   relative_growth_0_5h                    0.00000   0.00000  base       ✗
24   spread_bearing_sin                      0.00000   0.00000  base       ✗
25   spread_bearing_deg                      0.00000   0.00000  base       ✗
26   spread_bearing_cos                      0.00000   0.00000  base       ✗
27   speed_consistency                       0.00000   0.00000  enriched   ✗
28   reliable_slope                          0.00000   0.00000  enriched   ✗
29   reliable_eta_ci                         0.00000   0.00000  enriched   ✗
30   reliable_accel                          0.00000   0.00000  enriched   ✗
31   relative_accel                          0.00000   0.00000  enriched   ✗
32   log1p_speed_consistency                 0.00000   0.00000  enriched   ✗
33   radial_growth_rate_m_per_h              0.00000   0.00000  base       ✗
34   radial_growth_m                         0.00000   0.00000  base       ✗
35   radial_bearing_threat                   0.00000   0.00000  enriched   ✗
36   projected_advance_m                     0.00000   0.00000  base       ✗
37   momentum_threat                         0.00000   0.00000  enriched   ✗
38   log_area_ratio_0_5h                     0.00000   0.00000  base       ✗
39   log1p_threat_alignment                  0.00000   0.00000  enriched   ✗
40   is_approaching                          0.00000   0.00000  enriched   ✗
41   aligned_along_speed                     0.00000   0.00000  enriched   ✗
42   cross_track_component                   0.00000   0.00000  base       ✗
43   directional_growth                      0.00000   0.00000  enriched   ✗
44   alignment_cos                           0.00000   0.00000  base       ✗
45   along_track_speed                       0.00000   0.00000  base       ✗
46   area_growth_abs_0_5h                    0.00000   0.00000  base       ✗
47   area_growth_rate_ha_per_h               0.00000   0.00000  base       ✗
48   area_growth_rel_0_5h                    0.00000   0.00000  base       ✗
49   area_radial_threat                      0.00000   0.00000  enriched   ✗
50   bearing_threat_factor                   0.00000   0.00000  enriched   ✗
51   centroid_displacement_m                 0.00000   0.00000  base       ✗
52   centroid_speed_m_per_h                  0.00000   0.00000  base       ✗
53   closing_neg                             0.00000   0.00000  enriched   ✗
54   closing_pos                             0.00000   0.00000  enriched   ✗
55   closing_speed_abs_m_per_h               0.00000   0.00000  base       ✗
56   closing_speed_m_per_h                   0.00000   0.00000  base       ✗
57   cross_track_ratio                       0.00000   0.00000  enriched   ✗
58   threat_alignment                        0.00000   0.00000  enriched   ✗
59   dist_accel_m_per_h2                     0.00000   0.00000  base       ✗
60   dist_slope_ci_0_5h                      0.00000   0.00000  base       ✗
61   dist_change_norm                        0.00000   0.00000  enriched   ✗
62   dist_cv                                 0.00000   0.00000  enriched   ✗
63   dist_change_ci_0_5h                     0.00000   0.00000  base       ✗
64   dist_fit_r2_0_5h                        0.00000   0.00000  base       ✗
65   dist_std_ci_0_5h                        0.00000   0.00000  base       ✗
66   alignment_x_nperim                     -0.00000   0.00079  enriched   ✗
67   eta_bearing_adjusted                   -0.00001   0.00074  enriched   ✗
68   alignment_abs                          -0.00003   0.00034  base       ✗
69   is_high_wind_hour                      -0.00006   0.00004  enriched   ✗
70   log1p_area_first                       -0.00006   0.00080  base       ✗
71   event_start_hour                       -0.00007   0.00132  base       ✗
72   area_first_ha                          -0.00017   0.00032  base       ✗

{'rsf': ['log1p_dist_min',
  'eta_along_track',
  'eta_projected',
  'eta_closing',
  'eta_aligned_along',
  'eta_radial',
  'eta_combined',
  'eta_bearing_adjusted',
  'alignment_x_nperim',
  'dt_first_last_0_5h',
  'alignment_abs',
  'dt_x_alignment',
  'dist_per_area',
  'low_temporal_resolution_0_5h'],
 'gradboost': ['log1p_dist_min',
  'eta_closing',
  'dist_per_area',
  'eta_aligned_along',
  'dt_first_last_0_5h',
  'eta_projected',
  'eta_along_track'],
 'coxnet': ['log1p_dist_min',
  'num_perimeters_0_5h',
  'dist_per_area',
  'log1p_area_first',
  'dt_first_last_0_5h',
  'alignment_abs',
  'area_speed_ratio',
  'eta_closing',
  'alignment_x_nperim',
  'dist_fit_r2_0_5h',
  'dist_cv',
  'cross_track_component',
  'eta_projected',
  'reliable_accel',
  'dt_x_alignment',
  'dist_change_norm',
  'directional_growth',
  'log1p_reliable_slope',
  'dist_slope_ci_0_5h',
  'growth_pressure',
  'spread_bearing_sin',
  'area_first_ha',
  'low_temporal_resolution_0_5h',
  'event_start_month',
  'reliable_eta_ci',
  'spread_bearing_deg',
  'linear_eta_ci',
  'is_approaching'],
 'cgb': ['log1p_dist_min',
  'eta_closing',
  'alignment_abs',
  'eta_combined',
  'eta_aligned_along',
  'cross_track_component']}

### 6. Feature selection — inject custom wrapper

In [8]:
from xgbse import XGBSEDebiasedBCE
import numpy as np
from typing import Any
from dataclasses import field

class _XGBSurvivalFn:
    """
    Wrap one row of XGBSE predict DataFrame into a callable with .domain,
    similar to the sksurv step function interface that _survival_to_hit_probs expects.
    """
    __slots__ = ("times", "surv", "domain")

    def __init__(self, times: np.ndarray, surv: np.ndarray):
        self.times  = times
        self.surv   = np.clip(surv, 0.0, 1.0)
        self.domain = (float(times[0]), float(times[-1]))

    def __call__(self, t: float) -> float:
        return float(np.interp(t, self.times, self.surv,
                               left=self.surv[0], right=self.surv[-1]))

class XGBSEStrategy(ModelStrategy):
    """
    XGBSEDebiasedBCE survival strategy.
    Self resolve time_bins from training labels in fit().
    """

    def __init__(
        self,
        n_estimators:     int   = 200,
        learning_rate:    float = 0.05,
        max_depth:        int   = 4,
        subsample:        float = 0.8,
        colsample_bytree: float = 0.8,
        n_time_bins:      int   = 20,
    ):
        self.n_estimators     = n_estimators
        self.learning_rate    = learning_rate
        self.max_depth        = max_depth
        self.subsample        = subsample
        self.colsample_bytree = colsample_bytree
        self.n_time_bins      = n_time_bins
        self._time_bins       = None

    """
    XGBSEDebiasedBCE survival strategy.

    Self resolve time_bins from training labels in fit(),
    do not require user to specify
    """

    @property
    def name(self) -> str:
        return "XGBSE"

    # ── auto_params: scale by dataset size──────────────
    def auto_params(self, n: int) -> None:
        self.n_estimators = int(min(500, max(100, n * 1.0)))
        self.n_time_bins  = max(10, min(30, n // 10))

    # ── build: init model not fit ───────────────────────────────
    def build(self, random_state: int) -> XGBSEDebiasedBCE:
        return XGBSEDebiasedBCE(
            xgb_params={
                "n_estimators":     self.n_estimators,
                "learning_rate":    self.learning_rate,
                "max_depth":        self.max_depth,
                "subsample":        self.subsample,
                "colsample_bytree": self.colsample_bytree,
                "use_label_encoder": False,
                "eval_metric":      "logloss",
                "random_state":     random_state,
            }
        )

    # ── fit: resolve time_bins from label, then fit ─────────────────────
    def fit(self, model: XGBSEDebiasedBCE, X: np.ndarray, y: Any) -> Any:
        # y is structured array from Surv.from_dataframe
        # default field names of sksurv: y.dtype.names[0]=event, [1]=time
        event_field, time_field = y.dtype.names
        times  = y[time_field]
        events = y[event_field].astype(bool)

        # Use percentiles of event times to create bins (skip censored)
        event_times = times[events] if events.any() else times
        self._time_bins = np.unique(
            np.percentile(event_times,
                          np.linspace(0, 100, self.n_time_bins + 1))
        )

        model.fit(X, y, time_bins=self._time_bins)
        return model

    # ── predict_survival: return list callable with .domain ───────────────
    def predict_survival(self, model: XGBSEDebiasedBCE, X: np.ndarray) -> list:
        df: pd.DataFrame = model.predict(X)          # (n_samples, n_times)
        times = np.array(df.columns, dtype=float)    # time points from training

        # XGBSE returns survival P(T > t), NOT CDF
        # → use directly, do not need 1 - df
        surv_matrix = df.values                      # shape (n, T)

        return [
            _XGBSurvivalFn(times, surv_matrix[i])
            for i in range(len(surv_matrix))
        ]

    def summary_str(self) -> str:
        bins_str = (
            f"[{self._time_bins[0]:.0f}…{self._time_bins[-1]:.0f}]"
            if self._time_bins is not None else "not fit yet"
        )
        return (
            f"[XGBSE] n_est={self.n_estimators}  lr={self.learning_rate}  "
            f"depth={self.max_depth}  time_bins={len(self._time_bins) if self._time_bins is not None else '?'} {bins_str}"
        )

result = filter_features(
    enriched_train_df,
    base_features,
    enriched_features,
    n_repeats=10,
    wrapper=_TrainerWrapper(
        feature_cols=list(set(base_features + enriched_features)),
        strategy=XGBSEStrategy(n_estimators=200, learning_rate=0.05),
    ),
)

Features — Base: 33 | Enriched: 47 | Total: 80
  Fold 1 | XGBSE baseline: 0.9303
  Fold 2 | XGBSE baseline: 0.9212
  Fold 3 | XGBSE baseline: 0.9393

============================================================================
  Permutation Importance [XGBSE]
============================================================================
#    Feature                              Importance   FoldStd  Type       Mark
============================================================================
1    log1p_dist_min                          0.10721   0.09961  enriched   ★
2    eta_projected                           0.09873   0.12038  enriched   ★
3    eta_closing                             0.01204   0.01440  enriched   ★
4    dt_first_last_0_5h                      0.00606   0.00368  base       ★
5    eta_along_track                         0.00335   0.00580  enriched   +
6    dist_per_area                           0.00325   0.00299  enriched   +
7    num_perimeters_0_5h                     0.00233   0.00257  base       +
8    alignment_x_nperim                      0.00173   0.00283  enriched   +
9    area_speed_ratio                        0.00144   0.00128  enriched   +
10   alignment_abs                           0.00133   0.00220  base       +
11   spread_bearing_deg                      0.00126   0.00218  base       +
12   event_start_hour                        0.00092   0.00127  base       +
13   dt_x_alignment                          0.00064   0.00169  enriched   +
14   event_start_month                       0.00042   0.00087  base       +
15   dist_cv                                 0.00021   0.00031  enriched   +
16   hour_sin                                0.00012   0.00010  enriched   +
17   spread_bearing_cos                      0.00012   0.00020  base       +
18   centroid_speed_m_per_h                  0.00005   0.00009  base       +
19   projected_advance_m                     0.00000   0.00000  base       ✗
20   log1p_dist_slope                        0.00000   0.00000  enriched   ✗
21   is_high_wind_hour                       0.00000   0.00000  enriched   ✗
22   linear_eta_ci                           0.00000   0.00000  enriched   ✗
23   speed_consistency                       0.00000   0.00000  enriched   ✗
24   log1p_centroid_speed                    0.00000   0.00000  enriched   ✗
25   log1p_closing_speed                     0.00000   0.00000  enriched   ✗
26   reliable_slope                          0.00000   0.00000  enriched   ✗
27   log1p_dist_change                       0.00000   0.00000  enriched   ✗
28   reliable_eta_ci                         0.00000   0.00000  enriched   ✗
29   reliable_accel                          0.00000   0.00000  enriched   ✗
30   relative_growth_0_5h                    0.00000   0.00000  base       ✗
31   relative_accel                          0.00000   0.00000  enriched   ✗
32   radial_bearing_threat                   0.00000   0.00000  enriched   ✗
33   radial_growth_rate_m_per_h              0.00000   0.00000  base       ✗
34   log1p_dist_std                          0.00000   0.00000  enriched   ✗
35   log1p_growth                            0.00000   0.00000  base       ✗
36   log1p_projected                         0.00000   0.00000  enriched   ✗
37   radial_growth_m                         0.00000   0.00000  base       ✗
38   log1p_radial_growth                     0.00000   0.00000  enriched   ✗
39   is_approaching                          0.00000   0.00000  enriched   ✗
40   log1p_threat_alignment                  0.00000   0.00000  enriched   ✗
41   log_area_ratio_0_5h                     0.00000   0.00000  base       ✗
42   low_temporal_resolution_0_5h            0.00000   0.00000  base       ✗
43   momentum_threat                         0.00000   0.00000  enriched   ✗
44   log1p_radial_growth_rate                0.00000   0.00000  enriched   ✗
45   aligned_along_speed                     0.00000   0.00000  enriched   ✗
46   directional_growth                      0.00000   0.00000  enriched   ✗
47   dist_accel_m_per_h2                     0.00000   0.00000  base       ✗
48   along_track_speed                       0.00000   0.00000  base       ✗
49   area_growth_abs_0_5h                    0.00000   0.00000  base       ✗
50   area_growth_rate_ha_per_h               0.00000   0.00000  base       ✗
51   area_growth_rel_0_5h                    0.00000   0.00000  base       ✗
52   area_radial_threat                      0.00000   0.00000  enriched   ✗
53   bearing_threat_factor                   0.00000   0.00000  enriched   ✗
54   centroid_displacement_m                 0.00000   0.00000  base       ✗
55   closing_neg                             0.00000   0.00000  enriched   ✗
56   closing_pos                             0.00000   0.00000  enriched   ✗
57   closing_speed_abs_m_per_h               0.00000   0.00000  base       ✗
58   closing_speed_m_per_h                   0.00000   0.00000  base       ✗
59   cross_track_ratio                       0.00000   0.00000  enriched   ✗
60   growth_pressure                         0.00000   0.00000  enriched   ✗
61   threat_alignment                        0.00000   0.00000  enriched   ✗
62   dist_change_ci_0_5h                     0.00000   0.00000  base       ✗
63   dist_change_norm                        0.00000   0.00000  enriched   ✗
64   dist_slope_ci_0_5h                      0.00000   0.00000  base       ✗
65   dist_std_ci_0_5h                        0.00000   0.00000  base       ✗
66   eta_aligned_along                       0.00000   0.00000  enriched   ✗
67   eta_radial                              0.00000   0.00000  enriched   ✗
68   area_first_ha                          -0.00003   0.00006  base       ✗
69   dist_fit_r2_0_5h                       -0.00008   0.00014  base       ✗
70   log1p_centroid_disp                    -0.00011   0.00025  enriched   ✗
71   event_start_dayofweek                  -0.00011   0.00041  base       ✗
72   spread_bearing_sin                     -0.00012   0.00021  base       ✗
73   alignment_cos                          -0.00012   0.00057  base       ✗
74   cross_track_component                  -0.00017   0.00037  base       ✗
75   log1p_speed_consistency                -0.00017   0.00030  enriched   ✗
76   log1p_reliable_slope                   -0.00043   0.00074  enriched   ✗
77   eta_bearing_adjusted                   -0.00055   0.00096  enriched   ✗
78   log1p_area_first                       -0.00104   0.00161  base       ✗
79   eta_combined                           -0.00110   0.00216  enriched   ✗
80   hour_cos                               -0.00394   0.00620  enriched   ✗
============================================================================

── Summary by type ──
  base      : 8/33 positive | top-3: ['dt_first_last_0_5h', 'num_perimeters_0_5h', 'alignment_abs']
  enriched  : 10/47 positive | top-3: ['log1p_dist_min', 'eta_projected', 'eta_closing']

TIER1 (4):
  log1p_dist_min                      imp= 0.10721  std= 0.09961  ratio=0.9x
  eta_projected                       imp= 0.09873  std= 0.12038  ratio=1.2x
  eta_closing                         imp= 0.01204  std= 0.01440  ratio=1.2x
  dt_first_last_0_5h                  imp= 0.00606  std= 0.00368  ratio=0.6x

TIER2 (9):
  eta_along_track                     imp= 0.00335  std= 0.00580  ratio=1.7x
  dist_per_area                       imp= 0.00325  std= 0.00299  ratio=0.9x
  num_perimeters_0_5h                 imp= 0.00233  std= 0.00257  ratio=1.1x
  alignment_x_nperim                  imp= 0.00173  std= 0.00283  ratio=1.6x
  area_speed_ratio                    imp= 0.00144  std= 0.00128  ratio=0.9x
  alignment_abs                       imp= 0.00133  std= 0.00220  ratio=1.6x
  spread_bearing_deg                  imp= 0.00126  std= 0.00218  ratio=1.7x
  event_start_hour                    imp= 0.00092  std= 0.00127  ratio=1.4x
  dt_x_alignment                      imp= 0.00064  std= 0.00169  ratio=2.7x

TIER3 (5):
  event_start_month                   imp= 0.00042  std= 0.00087  ratio=2.1x
  dist_cv                             imp= 0.00021  std= 0.00031  ratio=1.5x
  hour_sin                            imp= 0.00012  std= 0.00010  ratio=0.9x
  spread_bearing_cos                  imp= 0.00012  std= 0.00020  ratio=1.7x
  centroid_speed_m_per_h              imp= 0.00005  std= 0.00009  ratio=1.7x

DROP (62):
  projected_advance_m                 imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_slope                    imp= 0.00000  std= 0.00000  ratio=0.0x
  is_high_wind_hour                   imp= 0.00000  std= 0.00000  ratio=0.0x
  linear_eta_ci                       imp= 0.00000  std= 0.00000  ratio=0.0x
  speed_consistency                   imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_centroid_speed                imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_closing_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_slope                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_change                   imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_eta_ci                     imp= 0.00000  std= 0.00000  ratio=0.0x
  reliable_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  relative_growth_0_5h                imp= 0.00000  std= 0.00000  ratio=0.0x
  relative_accel                      imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_bearing_threat               imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_growth_rate_m_per_h          imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_dist_std                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_growth                        imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_projected                     imp= 0.00000  std= 0.00000  ratio=0.0x
  radial_growth_m                     imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_radial_growth                 imp= 0.00000  std= 0.00000  ratio=0.0x
  is_approaching                      imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_threat_alignment              imp= 0.00000  std= 0.00000  ratio=0.0x
  log_area_ratio_0_5h                 imp= 0.00000  std= 0.00000  ratio=0.0x
  low_temporal_resolution_0_5h        imp= 0.00000  std= 0.00000  ratio=0.0x
  momentum_threat                     imp= 0.00000  std= 0.00000  ratio=0.0x
  log1p_radial_growth_rate            imp= 0.00000  std= 0.00000  ratio=0.0x
  aligned_along_speed                 imp= 0.00000  std= 0.00000  ratio=0.0x
  directional_growth                  imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_accel_m_per_h2                 imp= 0.00000  std= 0.00000  ratio=0.0x
  along_track_speed                   imp= 0.00000  std= 0.00000  ratio=0.0x
  area_growth_abs_0_5h                imp= 0.00000  std= 0.00000  ratio=0.0x
  area_growth_rate_ha_per_h           imp= 0.00000  std= 0.00000  ratio=0.0x
  area_growth_rel_0_5h                imp= 0.00000  std= 0.00000  ratio=0.0x
  area_radial_threat                  imp= 0.00000  std= 0.00000  ratio=0.0x
  bearing_threat_factor               imp= 0.00000  std= 0.00000  ratio=0.0x
  centroid_displacement_m             imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_neg                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_pos                         imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_abs_m_per_h           imp= 0.00000  std= 0.00000  ratio=0.0x
  closing_speed_m_per_h               imp= 0.00000  std= 0.00000  ratio=0.0x
  cross_track_ratio                   imp= 0.00000  std= 0.00000  ratio=0.0x
  growth_pressure                     imp= 0.00000  std= 0.00000  ratio=0.0x
  threat_alignment                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_ci_0_5h                 imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_change_norm                    imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_slope_ci_0_5h                  imp= 0.00000  std= 0.00000  ratio=0.0x
  dist_std_ci_0_5h                    imp= 0.00000  std= 0.00000  ratio=0.0x
  eta_aligned_along                   imp= 0.00000  std= 0.00000  ratio=0.0x
  eta_radial                          imp= 0.00000  std= 0.00000  ratio=0.0x
  area_first_ha                       imp=-0.00003  std= 0.00006  ratio=-1.7x
  dist_fit_r2_0_5h                    imp=-0.00008  std= 0.00014  ratio=-1.7x
  log1p_centroid_disp                 imp=-0.00011  std= 0.00025  ratio=-2.3x
  event_start_dayofweek               imp=-0.00011  std= 0.00041  ratio=-3.6x
  spread_bearing_sin                  imp=-0.00012  std= 0.00021  ratio=-1.7x
  alignment_cos                       imp=-0.00012  std= 0.00057  ratio=-4.6x
  cross_track_component               imp=-0.00017  std= 0.00037  ratio=-2.2x
  log1p_speed_consistency             imp=-0.00017  std= 0.00030  ratio=-1.7x
  log1p_reliable_slope                imp=-0.00043  std= 0.00074  ratio=-1.7x
  eta_bearing_adjusted                imp=-0.00055  std= 0.00096  ratio=-1.7x
  log1p_area_first                    imp=-0.00104  std= 0.00161  ratio=-1.5x
  eta_combined                        imp=-0.00110  std= 0.00216  ratio=-2.0x
  hour_cos                            imp=-0.00394  std= 0.00620  ratio=-1.6x

Survival features (TIER1 + TIER2): 13
['log1p_dist_min', 'eta_projected', 'eta_closing', 'dt_first_last_0_5h', 'eta_along_track', 'dist_per_area', 'num_perimeters_0_5h', 'alignment_x_nperim', 'area_speed_ratio', 'alignment_abs', 'spread_bearing_deg', 'event_start_hour', 'dt_x_alignment']